# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CCDebugiOS' do
    pod 'CCStat'
    pod 'CCDebug'
end

target 'CCDebugOSX' do
    pod 'CCDebug'
end
