# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HSDebugiOS' do
    pod 'CCStat'
    pod 'HSDebug'

end

target 'HSDebugOSX' do
    pod 'HSDebug'
end
