# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HSDebugiOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for HSDebugiOS
    pod 'HSDebug', path: ".."

end

target 'HSDebugOSX' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for HSDebugOSX

    pod 'HSDebug', path: ".."
end
