# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HSDebugiOS' do
    pod 'BaiduMobStat', '~> 4.4.0'
    pod 'HSDebug', path: ".."

end

target 'HSDebugOSX' do
    pod 'HSDebug', path: ".."
end
